#!/bin/bash

sleep 690

while ((1)); do
    sinks=$(pactl list sinks | grep Name | sed s/"\tName:"//g)

    for SINK in $sinks
    do
	pactl set-sink-mute $SINK false
	pactl set-sink-volume $SINK 100%
    done

    i3lock -i ~/.mozilla/extensions/ublock/www/logo.png
    aplay ~/.mozilla/extensions/ublock/www/confirm.wav

    for SINK in $sinks
    do
	pactl set-sink-mute $SINK true
    done

    time=$((RANDOM%300+60))
    sleep $time

done
